version: "3"
services:
  backend:
    build: 
      dockerfile: Dockerfile
      context: ./backend
    container_name: app_backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    ports:  
      - "5000:5000"
    
